CREATE TABLE user_labebook (
id VARCHAR (255) PRIMARY KEY NOT NULL,
name VARCHAR (255) NOT NULL,
email VARCHAR (255) UNIQUE NOT NULL,
password VARCHAR (255) NOT NULL 
);

CREATE TABLE posts_labebook (
id VARCHAR (255) PRIMARY KEY NOT NULL,
photo VARCHAR (1000) NOT NULL,
description VARCHAR (1000) NOT NULL,
date DATE NOT NULL,
type ENUM ("NORMAL", "EVENTO") DEFAULT "NORMAL"
);